<?php

namespace Database\Seeders;

use App\Models\Projet;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProjetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $projets = [
            [
                'titre' => 'Projet Melloussa',
                'description' => 'Etudes Technique Et Suivi Des Travaux Du Projet De Mise A Niveau',
                'status' => 'en cours',
                'num_marche_interne' => 2,
                'num_marche_externe' => 'MELLOUSSA/FA/14',
                'maitre_ouvrage' => 'APDN',
                'objet_marche' => 'Etudes Technique Et Suivi Des Travaux Du Projet De Mise A Niveau',
                'date_osc' => '2018-09-03',
                'delai_execution' => null,
                'lieu_execution' => 'Mellousssa',
                'type_marche' => 'S.Etude/Suivi',
                'domaine' => 'Infrastructure',
                'coordonnee_x' => 35.7595,
                'coordonnee_y' => -5.9214,
            ],
            [
                'titre' => 'Projet Taghramtf',
                'description' => 'La Réalisation De LEtude Technique Et Suivi Des Travaux Du',
                'status' => 'terminé',
                'num_marche_interne' => 3,
                'num_marche_externe' => 'TAGHRAMTFA/16',
                'maitre_ouvrage' => 'APDN',
                'objet_marche' => 'La Réalisation De LEtude Technique Et Suivi Des Travaux Du',
                'date_osc' => '2018-09-03',
                'delai_execution' => null,
                'lieu_execution' => 'Taghramtf',
                'type_marche' => 'S.Etude/Suivi',
                'domaine' => 'Infrastructure',
                'coordonnee_x' => 35.0752,
                'coordonnee_y' => -5.3698,
            ],
            [
                'titre' => 'Assistance Technique Al Hociema',
                'description' => 'Assistance Technique Au Maître DOuvrage Pour La Mise En Oeuvre Du Progr',
                'status' => 'terminé',
                'num_marche_interne' => 4,
                'num_marche_externe' => '16/AH/2018',
                'maitre_ouvrage' => 'AREP TTA',
                'objet_marche' => 'Assistance Technique Au Maître DOuvrage Pour La Mise En Oeuvre Du Progr',
                'date_osc' => null,
                'delai_execution' => 24,
                'lieu_execution' => 'Al Hociema',
                'type_marche' => 'S.Suivi',
                'domaine' => 'Bâtiment',
                'coordonnee_x' => 35.2494,
                'coordonnee_y' => -3.9382,
            ],
            [
                'titre' => 'Etablissement Des Metres Hoceima',
                'description' => 'Etablissement Des Metres Des Travaux Des Projets Dans La Province DAl Hoceima',
                'status' => 'terminé',
                'num_marche_interne' => 8,
                'num_marche_externe' => 'PMA/AH/267-19',
                'maitre_ouvrage' => 'APDN',
                'objet_marche' => 'Etablissement Des Metres Des Travaux Des Projets Dans La Province DAl Hoceima',
                'date_osc' => null,
                'delai_execution' => null,
                'lieu_execution' => 'Hoceima',
                'type_marche' => 'S.Etude',
                'domaine' => 'Infrastructure',
                'coordonnee_x' => 35.2518,
                'coordonnee_y' => -3.9372,
            ],
            [
                'titre' => 'Assistance Technique Ouezzane',
                'description' => 'Assistance Technique Pour La Mise À La Disposition Des Ress',
                'status' => 'terminé',
                'num_marche_interne' => 11,
                'num_marche_externe' => '21/DPA.OZ/SAHA/19',
                'maitre_ouvrage' => 'DPA dOuezzane',
                'objet_marche' => 'Assistance Technique Pour La Mise À La Disposition Des Ress',
                'date_osc' => '2019-10-21',
                'delai_execution' => 36,
                'lieu_execution' => 'Ouezzane',
                'type_marche' => 'S.Suivi',
                'domaine' => 'Hydraulique',
                'coordonnee_x' => 34.7956,
                'coordonnee_y' => -5.5768,
            ],
            [
                'titre' => 'Etude Piste Ain Beida',
                'description' => 'Etude Piste Ain Beida',
                'status' => 'terminé',
                'num_marche_interne' => 12,
                'num_marche_externe' => '01/2019',
                'maitre_ouvrage' => 'Provincial dOuezzane',
                'objet_marche' => 'Etude Piste Ain Beida',
                'date_osc' => '2019-11-07',
                'delai_execution' => 2,
                'lieu_execution' => 'Ain Beida',
                'type_marche' => 'S.Etude',
                'domaine' => 'Infrastructure',
                'coordonnee_x' => 34.8123,
                'coordonnee_y' => -5.5432,
            ],
            [
                'titre' => 'Assistance Technique DPA Ouezzane',
                'description' => 'Assistance Technique Pour La Mise À La Disposition De La Dp',
                'status' => 'terminé',
                'num_marche_interne' => 13,
                'num_marche_externe' => '31/DPA.OZ/SAHA/19',
                'maitre_ouvrage' => 'DPA dOuezzane',
                'objet_marche' => 'Assistance Technique Pour La Mise À La Disposition De La Dp',
                'date_osc' => '2020-02-03',
                'delai_execution' => 24,
                'lieu_execution' => 'Ouezzane',
                'type_marche' => 'S.Suivi',
                'domaine' => 'Hydraulique',
                'coordonnee_x' => 34.7956,
                'coordonnee_y' => -5.5768,
            ],
            [
                'titre' => 'Etudes Technique Chefchaouen',
                'description' => 'Etudes Technique Et Suivi Des Travaux Du Projet De Mise A N',
                'status' => 'en cours',
                'num_marche_interne' => 15,
                'num_marche_externe' => 'CH/545-19',
                'maitre_ouvrage' => 'APDN',
                'objet_marche' => 'Etudes Technique Et Suivi Des Travaux Du Projet De Mise A N',
                'date_osc' => '2019-12-06',
                'delai_execution' => null,
                'lieu_execution' => 'Chefchaouen',
                'type_marche' => 'S.Etude/Suivi',
                'domaine' => 'Infrastructure',
                'coordonnee_x' => 35.1686,
                'coordonnee_y' => -5.2634,
            ],
            [
                'titre' => 'Mission Assistance Chtouka Ait Baha',
                'description' => 'Mission DAssistance À Maîtrise DŒuvre Pour Le Contrôle E',
                'status' => 'en cours',
                'num_marche_interne' => 16,
                'num_marche_externe' => '10/2020',
                'maitre_ouvrage' => 'Province Chtouka Ait Baha',
                'objet_marche' => 'Mission DAssistance À Maîtrise DŒuvre Pour Le Contrôle E',
                'date_osc' => '2021-01-18',
                'delai_execution' => 18,
                'lieu_execution' => 'Chtouka Ait Baha',
                'type_marche' => 'S.Suivi',
                'domaine' => 'Environnement',
                'coordonnee_x' => 30.0667,
                'coordonnee_y' => -9.1500,
            ],
            [
                'titre' => 'Études De Dédoublement Chefchaouen',
                'description' => 'Études De Dédoublement De La Rr412 Du Pk9+100 Au Pk 15+',
                'status' => 'en cours',
                'num_marche_interne' => 17,
                'num_marche_externe' => 'DCT/ETUDES DEDO',
                'maitre_ouvrage' => 'APDN',
                'objet_marche' => 'Études De Dédoublement De La Rr412 Du Pk9+100 Au Pk 15+',
                'date_osc' => '2020-10-01',
                'delai_execution' => null,
                'lieu_execution' => 'Chefchaouen',
                'type_marche' => 'S.Etude',
                'domaine' => 'Infrastructure',
                'coordonnee_x' => 35.1686,
                'coordonnee_y' => -5.2634,
            ],
            [
                'titre' => 'Travaux Des Métrés Ouezzane',
                'description' => 'Travaux Des Métrés Des Projets Engagés Au Niveau De La Province DOuezzane',
                'status' => 'terminé',
                'num_marche_interne' => 19,
                'num_marche_externe' => '04/2020/BP',
                'maitre_ouvrage' => 'Provincial dOuezzane',
                'objet_marche' => 'Travaux Des Métrés Des Projets Engagés Au Niveau De La Province DOuezzane',
                'date_osc' => null,
                'delai_execution' => 24,
                'lieu_execution' => 'Ouezzane',
                'type_marche' => 'S.Suivi',
                'domaine' => 'Infrastructure',
                'coordonnee_x' => 34.7956,
                'coordonnee_y' => -5.5768,
            ],
        ];

        foreach ($projets as $projet) {
            Projet::create([
                'titre' => $projet['titre'],
                'slug' => Str::slug($projet['titre']),
                'description' => $projet['description'],
                'image' => null,
                'status' => $projet['status'],
                'num_marche_interne' => $projet['num_marche_interne'],
                'num_marche_externe' => $projet['num_marche_externe'],
                'maitre_ouvrage' => $projet['maitre_ouvrage'],
                'objet_marche' => $projet['objet_marche'],
                'date_osc' => $projet['date_osc'],
                'delai_execution' => $projet['delai_execution'],
                'lieu_execution' => $projet['lieu_execution'],
                'type_marche' => $projet['type_marche'],
                'domaine' => $projet['domaine'],
                'coordonnee_x' => $projet['coordonnee_x'],
                'coordonnee_y' => $projet['coordonnee_y'],
            ]);
        }
    }
}